import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Geist_Mono, Space_Grotesk, Libre_Baskerville } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Nav from '@/components/nav'
import Sidebar from '@/components/sidebar'

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

const libreBaskerville = Libre_Baskerville({
  variable: '--font-libre-baskerville',
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Houzel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`font-grotesk ${geistMono.variable} bg-white`}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          > */}
            <SignedOut>
              {children}
            </SignedOut>
            <SignedIn>
              <div className="flex flex-row w-full h-screen overflow-hidden">
                <Sidebar />
                <div className="flex flex-col w-full h-screen overflow-y-scroll">
                  {/* <Nav /> */}
                  {children}
                </div>
              </div>
            </SignedIn>
          {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  )
}